export class ScenesAroundMastercardPageObjects {
  OBJ_SAM_WEBPART_TITLE = "//div[@id='mc-sam-container']//div//h1"
  OBJ_SAM_SUBMIT_PHOTO_LINK = "text=Submit photo"
  OBJ_SAM_SUBMIT_PHOTO_POPUP = "//div[contains(@class,'submitDialogMainOverride')]"
  OBJ_SAM_CANCEL_BTN_ON_POPUP = "text=Cancel"
  OBJ_SAM_CHOOSE_FILE = "//input[@id='uploadFile']"
  OBJ_SAM_ADD_TO_TWITTER_CHECKBOX = "//div[contains(@class,'Checkbox')]//i[contains(@class,'checkmark')]"
  OBJ_SAM_PHOTO_CAPTION = "//textarea[contains(@id,'TextField')]"
  OBJ_SAM_UPLOAD_BTN = "//span[text()='Upload']"
  OBJ_SAM_SUCCESS_MSG = "//div[text()='Your picture has been submitted for approval!']"
  OBJ_SAM_NEXT_BTN = "text=Next"
  OBJ_SAM_DOTS = "//div[contains(@class,'SC-card-SAM mc-carousal')]//button//span[@class='dot']"
  OBJ_SAM_ACTIVE_CARDS = "//div[contains(@class,'SC-card-SAM mc-carousal')]//div[@class='slick-slide slick-active slick-cloned slick-current']//button"
  OBJ_SAM_IMAGE_POPUP = "//div[contains(@class,'ms-Dialog-main')]"
  OBJ_SAM_ACTIVE_CARD = "(//div[@id='mc-sam-container']//div[@class='mc-hub-surface-card-container']//div[contains(@class,'SC-card-SAM mc-carousal mc-sam-slider slick-initialized')]//button//div[contains(@class,'mc-hub--hero')])[1]"
  OBJ_SAM_CLOSE_BTN_ON_POPUP = "//div[contains(@class,'ms-Dialog-main')]//button[contains(@class,'close')]"
  OBJ_SAM_LIKE_ICON = "//span[@id='likes-container']//i[contains(@class,'Like')]"
  OBJ_SAM_VIEW_ALL_LINK = "//div[@id='mc-sam-container']//a[text()='View all']"
  OBJ_SAM_TITLES_ON_CARD = "//div[@class='ug-textpanel-title']"
  OBJ_SAM_CARDS_ON_LANDING_PAGE = "//div[@class='ug-thumb-wrapper ug-tile ug-thumb-ratio-set']//div[@class='ug-thumb-overlay']"
  OBJ_SAM_FIRST_CARD = "(//div[@class='ug-textpanel-title'])[1]"
  OBJ_SAM_IMAGE_LINK_LANDING_PAGE = "//a[@class='ug-tile-icon ug-icon-link']"
  OBJ_SAM_TITLE_ON_POPUP_CLASSIC = "//div[@class='mc-hub--hero']//div[@class='mc-photodialog-caption']"
} 